import "../app/globals.css";
import Layout from "@/app/Components/Layout";

export const metadata = {
  title: "Sankalp Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      
          <Layout>{children}</Layout>
       
      </body>
    </html>
  );
}
